### ISSUE TITLE
API to query begin/end offsets for a given topic?

### ISSUE THREAD

**Issue by FrancoisBeaune** [criteo/kafka-sharp#10]
Does kafka-sharp offer an offset API, e.g. to query begin/end offsets for a given topic?

**Comment by sdanzan** [comment]
No, currently the `ListOffset` API is only used privately in the `ConsumerRouter` and not publicly exposed.

**Comment by FrancoisBeaune** [comment]
Any chance to expose it? It would be really useful for our use case.

**Comment by sdanzan** [comment]
Could I have more insights on the use case?

**Comment by FrancoisBeaune** [comment]
Our principal use of knowing the last offset is to compute and monitor the "lag" of a consumer with respect to the end of a topic.

**Comment by FrancoisBeaune** [comment]
Another use case would be to consume up until that known end-of-topic and then stop consuming for a while (even if the actual end-of-topic has moved in the meantime), instead of blocking until either new messages have received or a timeout has expired.

**Comment by sdanzan** [comment]
Ok.

**Comment by sdanzan** [comment]
Two methods are now provided on `ClusterClient`: `GetLatestOffset` and `GetEarliestOffset`.

**Comment by FrancoisBeaune** [comment]
Oh brilliant, thanks!
