### ISSUE TITLE
Akka vs MassTransit vs Kafka

### ISSUE THREAD

**Issue by eaba** [criteo/kafka-sharp#14]
This is just a question bugging my mind. I want to understand how those three can play together.
What role would Kafka if we decided to use the three together?
Thanks

**Comment by sdanzan** [comment]
Kafka would be the underlying transport bus used by Mass Transit. However MT does not support it out of the box, you would have to write it yourself. Akka is an actor system that does happen to support actors distributed over a cluster, so you can use it as a message bus in scenarios where you don't need high scalabilty and you only have Akka based applications but it is not its primary purpose.

**Comment by eaba** [comment]
Thanks @sdanzan!

> However MT does not support it out of the box, you would have to write it yourself
Any guide from you?

> Akka is an actor system that does happen to support actors distributed over a cluster, so you can use it as a message bus in scenarios where you don't need high scalabilty and you only have Akka based applications but it is not its primary purpose

Can u shed more light......i want to ensure I understood that clearly. Thanks
