### ISSUE TITLE
Messages with null key will not be read

### ISSUE THREAD

**Issue by ArtemAstashkin** [criteo/kafka-sharp#16]
If Key of message equals null, KafkaConsumer will not invoke MessageReceived event.
I've found the special condition https://github.com/criteo/kafka-sharp/blob/master/kafka-sharp/kafka-sharp/Public/KafkaConsumer.cs#L150

And the same condition in KafkaProducer https://github.com/criteo/kafka-sharp/blob/master/kafka-sharp/kafka-sharp/Public/KafkaProducer.cs#L132

which means it will always return false if TKey is null - we can produce messages with key==null but can't receive it.

Is it possible to change condition to (kr.Key is TKey ||  TKey == null) ?

Thanks in advance.

**Comment by sdanzan** [comment]
Should be fixed now.

**Comment by ArtemAstashkin** [comment]
Thanks!
