### ISSUE TITLE
Roadmap / Kafka supported versions question

### ISSUE THREAD

**Issue by javierholguera** [criteo/kafka-sharp#3]
Hi,
I'm about to start a project that would require producing to and consuming from Kafka with C# and I'm having a review of the "state of the art" for C# Kafka client libraries. I came across your project and it looks very interesting. Do you have any idea about what would be the roadmap for the library? Features that you plan to add and stuff like that. The feature list is already impressive, but I wonder if there is anything you've already identified that you'd like to add.

My other question would be regarding how mature / tested the library is. Are you using it or know about anybody using it in Production? What versions of Kafka have you tested the library against? We probably will be using Kafka v0.10.

Thanks

**Comment by sdanzan** [comment]
Hi,

there is currently no real roadmap, however some new developments are
planned in the near future depending on our internal needs (but I would be
more than happy to integrate contributions).

More precise answers:

- this client is almost exclusively used in Produce scenarios (we have a
few .NET consumers but nothing at big scale, we mainly consume from JVM
applications).
- we use it in 24/24 applications. Clusters receives billions of messages
per day. Topics range from a few bytes per messages to dozen of k per
messages. Most applications send on several topics. Producer part is very
mature and has been tested extensively on large scale.
- We use it on Kafka 0.10 clusters but currently the driver doesn't use any
special 0.10 features.
- Focus on the next months will be on better support of 0.10 features and
better consumer support (with consumer groups).

-- 
Serge

2016-12-07 13:16 GMT+01:00 Javier Holguera <notifications@github.com>:

**Comment by javierholguera** [comment]
Thanks for your answer @sdanzan. It's clear now.

I'll close the issue.
