### ISSUE TITLE
what does "An established connection was aborted by the software in your host machine" mean

### ISSUE THREAD

**Issue by ricoisme** [criteo/kafka-sharp#30]
Hi 

I run consumer group under windows service.
Sometimes I have found Kafka.Network.TransportException issue from our log.

The error message as below:
Kafka.Network.TransportException: Kafka transport error ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   --- End of inner exception stack trace ---

does it mean our consumer group timeout? or leader changed in kafka server to cause Kafka.Network.TransportException?

although this issue did not much impact received of consumer  because consumer group will connect to another kafka server.

I would like to know root cause of this exception comes from windows service with kafka driver or kafka's config or else . 

Thanks

**Comment by ychuzevi** [comment]
Hello,

The driver is opening one socket per broker it needs a connection to. This exception indicates that one socket was closed without the driver's knowledge. We do get those on our Windows servers as well and it seems that the Kafka brokers sometimes close their connections unilaterally.

In any case, if there is a "serious" error (timeout, no partition available...), an appropriate message will be logged, hence the fact that this one is only a warning (and should not have any consequence as long as it does not happen too often).

**Comment by ricoisme** [comment]
I got it.
so , I can ignore this exception if our kafka cluster works fine.

Thanks

**Comment by ychuzevi** [comment]
Yes, sure
