### ISSUE TITLE
Producing on a topic that does not exist fails

### ISSUE THREAD

**Issue by kamiluigs** [criteo/kafka-sharp#31]
Wondering if this scenario is supported with this library...

I have verified that auto.create.topics.enable is set to true in the broker configuration.  Using ClusterClient.Produce(topic, key, data) yields the following error when the topic does not exist:

[Producer] No partition available for topic <topic_name> postponing messages.

Should this be supported and I am doing something wrong, or is this not supported?

Thanks!

**Comment by sdanzan** [comment]
This is not supported in this client.
