### ISSUE TITLE
Is this project still maintained ? Future plans ?

### ISSUE THREAD

**Issue by sirajmansour** [criteo/kafka-sharp#40]
The effort that has been put into this project is highly appreciated.
I was wondering if you guys have plans to maintain the project or if you have a roadmap ?

**Comment by ychuzevi** [comment]
Yes, the project is still maintained, we are using it in production.
Regarding the roadmap, we don’t have any plan to add big features as of today but this may change depending of the needs.
Please do share with us if you are thinking to something specific  or want to contribute.
Thanks!

**Comment by sirajmansour** [comment]
I was wondering if this is lacking any features that you know of, or has any known issues.. I am currently using https://github.com/confluentinc/confluent-kafka-dotnet which is just a a wrapper around `librdkafka` and it would be nice to know how the 2 libraries compare if anyone has done it before.

**Comment by ychuzevi** [comment]
A strong focus was placed on performance and resiliency.
We don't have any recent data though and we will definitely do a benchmark in the near future.
