### ISSUE TITLE
 topic auto creation not supported

### ISSUE THREAD

**Issue by vasicvuk** [criteo/kafka-sharp#43]
While producing data to topic i get following error:
```
[2019-01-02 10:16:58] ERROR [Producer] No partition available for topic some_topic, postponing messages.
```

In server.properties there is setting for auto topic creation and replication factor:
```
auto.create.topics.enable: true
default.replication.factor: 1
```

**Comment by ychuzevi** [comment]
Auto topic creation is actually not supported. If you create the topic, then you should be able to produce messages without issue.
This allows to make sure the messages are always written to the expected topics. Do you have a use case requiring to create multiple topics on the fly?

**Comment by sdanzan** [comment]
If the topic does not exist, the producer won't create it. This is intended, we don't want to support topic auto-creation because it is not a sound pattern.
