### ISSUE TITLE
Offset Issue

### ISSUE THREAD

**Issue by scotthellewell** [criteo/kafka-sharp#45]
Each time my consuming application restarts it is getting the last message that was committed as the first message in the MessageReceived.  Since that message has already been committed, it should be skipping it.  Is there some way to tell it to not give the last committed message?

**Comment by ychuzevi** [comment]
This should indeed not happen when relying on consumer group feature in order to read messages.

Do you start consuming by calling `Subscribe` method?

Would you be able to share a code snippet to reproduce the issue?
