### ISSUE TITLE
How to setup authentication?

### ISSUE THREAD

**Issue by holonsoftFounder** [criteo/kafka-sharp#48]
Hi,
thank you for your great effort and sharing this lib.
In our project I have to authenticate against KAFKA server:
SecurityProtocol.SaslSsl, SaslMechanism.ScramSha256, User, Pw

How do I achieve this?
Best regards
Christian

**Comment by ychuzevi** [comment]
Hi,
The driver does not support authentication yet. The plan is to add SASL OAuth in the coming months. There is no plan to add other authentication algorithm for the moment but the implementation will hopefully not be too hard to extend.
I hope this helps.
Best regards,
Yohan

**Comment by holonsoftFounder** [comment]
Thx a lot for info. I'll looking forward to your implementation.
